// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyMappingAndCalculate(arg1:string,arg2:main.ColumnMapConfig,arg3:main.ValueMapConfig):Promise<main.ApplyResult>;

export function AutoDetectColumns(arg1:string):Promise<main.AutoDetectResult>;

export function DefaultConfigSaveFileName(arg1:string,arg2:string):Promise<string>;

export function DefaultSaveFileName(arg1:string):Promise<string>;

export function GetAnalysisTable(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AnalysisTableResult>;

export function LoadCSVFile(arg1:string,arg2:string):Promise<main.CSVLoadResult>;

export function LoadColumnMapConfig(arg1:string):Promise<main.ColumnMapConfig>;

export function LoadProcessedCSV(arg1:string,arg2:string):Promise<main.ApplyResult>;

export function LoadValueMapConfig(arg1:string):Promise<main.ValueMapConfig>;

export function OpenCSVFileDialog():Promise<string>;

export function OpenJSONFileDialog():Promise<string>;

export function SaveColumnMapConfig(arg1:main.ColumnMapConfig,arg2:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveProcessedCSV(arg1:string,arg2:string):Promise<void>;

export function SaveValueMapConfig(arg1:main.ValueMapConfig,arg2:string):Promise<void>;
