// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMappingAndCalculate(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyMappingAndCalculate'](arg1, arg2, arg3);
}

export function AutoDetectColumns(arg1) {
  return window['go']['main']['App']['AutoDetectColumns'](arg1);
}

export function DefaultConfigSaveFileName(arg1, arg2) {
  return window['go']['main']['App']['DefaultConfigSaveFileName'](arg1, arg2);
}

export function DefaultSaveFileName(arg1) {
  return window['go']['main']['App']['DefaultSaveFileName'](arg1);
}

export function GetAnalysisTable(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAnalysisTable'](arg1, arg2, arg3, arg4);
}

export function LoadCSVFile(arg1, arg2) {
  return window['go']['main']['App']['LoadCSVFile'](arg1, arg2);
}

export function LoadColumnMapConfig(arg1) {
  return window['go']['main']['App']['LoadColumnMapConfig'](arg1);
}

export function LoadProcessedCSV(arg1, arg2) {
  return window['go']['main']['App']['LoadProcessedCSV'](arg1, arg2);
}

export function LoadValueMapConfig(arg1) {
  return window['go']['main']['App']['LoadValueMapConfig'](arg1);
}

export function OpenCSVFileDialog() {
  return window['go']['main']['App']['OpenCSVFileDialog']();
}

export function OpenJSONFileDialog() {
  return window['go']['main']['App']['OpenJSONFileDialog']();
}

export function SaveColumnMapConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveColumnMapConfig'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveProcessedCSV(arg1, arg2) {
  return window['go']['main']['App']['SaveProcessedCSV'](arg1, arg2);
}

export function SaveValueMapConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveValueMapConfig'](arg1, arg2);
}
